### ISSUE TITLE
Calling Client.update() causes a Null Object Reference

### ISSUE THREAD

**Issue by Jarrio** [5Mixer/mphx#39]
Some code for context:

```
private var clientConnection:Client;
override public function create():Void {
    super.create();
    clientConnection = new Client("127.0.0.1", 8000);
    clientConnection.connect();
}
```

This works fine calling `clientConnection.connected` returns true, as it should. But when I add `clientConnection.update()` to the haxeflixel update() call the thing crashes with the following error:

Thread 0 (critical error: Null Object Reference):

>    19 : sys.net.Socket.select() at P:\Development\HaxeToolkit\haxe\std/cpp/_std/sys/net/Socket.hx:227
>      18 : mphx.client.impl.TcpClient.update() at mphx/client/impl/TcpClient.hx:87
>      17 : PlayState.update() at PlayState.hx:23
>      16 : flixel.FlxState.tryUpdate() at flixel/FlxState.hx:168
>      15 : flixel.FlxGame.update() at flixel/FlxGame.hx:750
>      14 : flixel.FlxGame.step() at flixel/FlxGame.hx:674
>      13 : flixel.FlxGame.onEnterFrame() at flixel/FlxGame.hx:541
>      12 : openfl._legacy.events.EventDispatcher.dispatchEvent() at openfl/_legacy/events/EventDispatcher.hx:98
>      11 : openfl._legacy.display.DisplayObject.__dispatchEvent() at openfl/_legacy/display/DisplayObject.hx:182
>      10 : openfl._legacy.display.DisplayObject.__broadcast() at openfl/_legacy/display/DisplayObject.hx:161
>      9 : openfl._legacy.display.DisplayObjectContainer.__broadcast() at openfl/_legacy/display/DisplayObjectContainer.hx:286
>      8 : openfl._legacy.display.Stage.__render() at openfl/_legacy/display/Stage.hx:1103
>      7 : openfl._legacy.display.Stage.__checkRender() at openfl/_legacy/display/Stage.hx:351
>      6 : openfl._legacy.display.Stage.__pollTimers() at openfl/_legacy/display/Stage.hx:1084
>      5 : openfl._legacy.display.Stage.__doProcessStageEvent() at openfl/_legacy/display/Stage.hx:430
>      4 : openfl._legacy.display.Stage.__processStageEvent() at openfl/_legacy/display/Stage.hx:571
>      3 : extern.cffi() at P:/Development/HaxeToolkit/haxe/lib/hxcpp/3,3,49/src/hx/Lib.cpp:182
>      2 : openfl._legacy.Lib.create() at openfl/_legacy/Lib.hx:104
>      1 : ApplicationMain.main() at ApplicationMain.hx:52
>      0 : hxcpp.__hxcpp_main() at ?:1

**Comment by Jarrio** [comment]
For anyone who has this issue I was able to fix it by placing the `clientConnection.update()` call before the `super.update(elapsed)` call

**Comment by 5Mixer** [comment]
You closed and reopened this - I'm presuming that the issue still exists. Not really sure what to think of this issue yet - socket.select seems broken. This is the case with haxe 3.3.0, which, according to your other comment, you have mitigated by upgrading haxe to a dev build. Are you able to check your haxe version, ensure mphx is the latest git version, and if that doesn't work, provide more information (more code/platform/os). Thanks!

**Comment by ghost** [comment]
```
if(clientConnection != null) {
  clientConnection.update()
}
```

This should fix it. The update function is triggerd straight away and there for has not yet recieved the valid socket.

**Comment by Jarrio** [comment]
@lj222kj Hmm, this didn't fix the issue. In the same spirit I attempted doing      

```
if(clientConnection.connected) {
    clientConnection.update();
}
```

 which lead to the same result. Also `clientConnection` is not null [(socket values at the time of the crash)](http://puu.sh/qtwKl/3e929f2992.png). 

@5Mixer I reset mphx to the git version, My versions are:

haxe: 3.3.0-rc1 dev build released on July 31st 2016 (I have tried to compile with other versions and got the same issues)
flixel: 4.1.0
openfl: 3.6.1
lime: 2.9.1

I am able to create this issue in a brand new project file:

```
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.group.FlxGroup.FlxTypedGroup;
import flixel.FlxG;
import source.entities.Player;

import mphx.client.Client;

class PlayState extends FlxState {
    public var socket:Client;

    public var player:Player;
    public var allPlayers:FlxTypedGroup<Player>;    
    public var players = new Map<String, Player>();

    override public function create():Void {
        super.create();
        FlxG.autoPause = false;

        allPlayers = new FlxTypedGroup<Player>();
        add(allPlayers);

        socket = new Client("127.0.0.1", 8000);
        socket.connect();

    }

    override public function update(elapsed:Float):Void {
        if (socket != null && socket.connected) {
            socket.update();
        }
        super.update(elapsed);
    }
} 
```

The Player class is empty at the moment it only extends FlxSprite and has a constructor which sets x/y

I am compiling to cpp/windows running on Windows 10 64bit

**Comment by 5Mixer** [comment]
Crap I left this a long time. Sorry, I have a tendency to forget issues sometimes. It's probably too late for this now, but do you remember if you had a server running? It might sound silly, and this should technically not crash, but I'm interested in resolving this.

**Comment by Jarrio** [comment]
In the picture I posted above I showed that I was connected to the server. I ended up dropping mphx and making my own library. But then later found that the issue was with openfl, not with your library so do not worry! I made a manual edit to the openfl socket file? (can't remember) and got everything working fine with my own library(and yours!)
